POST http://localhost:8765/hook
Content-Type: application/json
Accept: application/json
X-Gitee-Event: Merge Request Hook

{
  "action": "open",
  "action_desc": null,
  "pull_request": {
    "id": 3190449,
    "number": 5,
    "state": "open",
    "html_url": "https://gitee.com/open-euler/syncbot-example/pulls/5",
    "diff_url": "https://gitee.com/open-euler/syncbot-example/pulls/5.diff",
    "patch_url": "https://gitee.com/open-euler/syncbot-example/pulls/5.patch",
    "title": "hello",
    "body": "world",
    "labels": [],
    "languages": [],
    "created_at": "2020-12-07T22:09:35+08:00",
    "updated_at": "2020-12-07T22:09:35+08:00",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": null,
    "merge_reference_name": "refs/pull/5/MERGE",
    "user": {
      "id": 341810,
      "name": "syncBot",
      "email": "custa@126.com",
      "username": "sync-bot",
      "user_name": "sync-bot",
      "url": "https://gitee.com/sync-bot",
      "login": "sync-bot",
      "avatar_url": "https://gitee.com/assets/no_portrait.png",
      "html_url": "https://gitee.com/sync-bot",
      "type": "User",
      "site_admin": false
    },
    "assignee": null,
    "assignees": [],
    "tester": null,
    "testers": [],
    "need_test": false,
    "need_review": true,
    "milestone": null,
    "head": {
      "label": "openEuler:branch3",
      "ref": "branch3",
      "sha": "49ffd07b2ce6e1a5751426f07624d9701a08fb98",
      "user": {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 12940005,
        "name": "syncbotExample",
        "path": "syncbot-example",
        "full_name": "open-euler/syncbot-example",
        "owner": {
          "id": 341810,
          "name": "syncBot",
          "email": "custa@126.com",
          "username": "sync-bot",
          "user_name": "sync-bot",
          "url": "https://gitee.com/sync-bot",
          "login": "sync-bot",
          "avatar_url": "https://gitee.com/assets/no_portrait.png",
          "html_url": "https://gitee.com/sync-bot",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://gitee.com/open-euler/syncbot-example",
        "url": "https://gitee.com/open-euler/syncbot-example",
        "description": "syncbot-example 示例",
        "fork": false,
        "created_at": "2020-11-27T11:18:01+08:00",
        "updated_at": "2020-12-07T22:08:38+08:00",
        "pushed_at": "2020-12-07T22:06:04+08:00",
        "git_url": "git://gitee.com/open-euler/syncbot-example.git",
        "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
        "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
        "svn_url": "svn://gitee.com/open-euler/syncbot-example",
        "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
        "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
        "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
        "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
        "stargazers_count": 0,
        "watchers_count": 1,
        "forks_count": 1,
        "language": "其他",
        "has_issues": true,
        "has_wiki": true,
        "has_pages": false,
        "license": "MulanPSL-2.0",
        "open_issues_count": 0,
        "default_branch": "master",
        "namespace": "open-euler",
        "name_with_namespace": "openEuler/syncbotExample",
        "path_with_namespace": "open-euler/syncbot-example"
      }
    },
    "base": {
      "label": "openEuler:master",
      "ref": "master",
      "sha": "e3824b36a115b1f640c490d8141a9bae1c1667ab",
      "user": {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 12940005,
        "name": "syncbotExample",
        "path": "syncbot-example",
        "full_name": "open-euler/syncbot-example",
        "owner": {
          "id": 341810,
          "name": "syncBot",
          "email": "custa@126.com",
          "username": "sync-bot",
          "user_name": "sync-bot",
          "url": "https://gitee.com/sync-bot",
          "login": "sync-bot",
          "avatar_url": "https://gitee.com/assets/no_portrait.png",
          "html_url": "https://gitee.com/sync-bot",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://gitee.com/open-euler/syncbot-example",
        "url": "https://gitee.com/open-euler/syncbot-example",
        "description": "syncbot-example 示例",
        "fork": false,
        "created_at": "2020-11-27T11:18:01+08:00",
        "updated_at": "2020-12-07T22:08:38+08:00",
        "pushed_at": "2020-12-07T22:06:04+08:00",
        "git_url": "git://gitee.com/open-euler/syncbot-example.git",
        "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
        "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
        "svn_url": "svn://gitee.com/open-euler/syncbot-example",
        "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
        "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
        "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
        "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
        "stargazers_count": 0,
        "watchers_count": 1,
        "forks_count": 1,
        "language": "其他",
        "has_issues": true,
        "has_wiki": true,
        "has_pages": false,
        "license": "MulanPSL-2.0",
        "open_issues_count": 0,
        "default_branch": "master",
        "namespace": "open-euler",
        "name_with_namespace": "openEuler/syncbotExample",
        "path_with_namespace": "open-euler/syncbot-example"
      }
    },
    "merged": false,
    "mergeable": true,
    "merge_status": "unchecked",
    "updated_by": {
      "id": 341810,
      "name": "syncBot",
      "email": "custa@126.com",
      "username": "sync-bot",
      "user_name": "sync-bot",
      "url": "https://gitee.com/sync-bot",
      "login": "sync-bot",
      "avatar_url": "https://gitee.com/assets/no_portrait.png",
      "html_url": "https://gitee.com/sync-bot",
      "type": "User",
      "site_admin": false
    },
    "comments": 0,
    "commits": 1,
    "additions": 1,
    "deletions": 0,
    "changed_files": 1
  },
  "number": 5,
  "iid": 5,
  "title": "hello",
  "body": "world",
  "languages": [],
  "state": "open",
  "merge_status": "unchecked",
  "merge_commit_sha": null,
  "url": "https://gitee.com/open-euler/syncbot-example/pulls/5",
  "source_branch": "branch3",
  "source_repo": {
    "project": {
      "id": 12940005,
      "name": "syncbotExample",
      "path": "syncbot-example",
      "full_name": "open-euler/syncbot-example",
      "owner": {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://gitee.com/open-euler/syncbot-example",
      "url": "https://gitee.com/open-euler/syncbot-example",
      "description": "syncbot-example 示例",
      "fork": false,
      "created_at": "2020-11-27T11:18:01+08:00",
      "updated_at": "2020-12-07T22:08:38+08:00",
      "pushed_at": "2020-12-07T22:06:04+08:00",
      "git_url": "git://gitee.com/open-euler/syncbot-example.git",
      "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
      "svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
      "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
      "stargazers_count": 0,
      "watchers_count": 1,
      "forks_count": 1,
      "language": "其他",
      "has_issues": true,
      "has_wiki": true,
      "has_pages": false,
      "license": "MulanPSL-2.0",
      "open_issues_count": 0,
      "default_branch": "master",
      "namespace": "open-euler",
      "name_with_namespace": "openEuler/syncbotExample",
      "path_with_namespace": "open-euler/syncbot-example"
    },
    "repository": {
      "id": 12940005,
      "name": "syncbotExample",
      "path": "syncbot-example",
      "full_name": "open-euler/syncbot-example",
      "owner": {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://gitee.com/open-euler/syncbot-example",
      "url": "https://gitee.com/open-euler/syncbot-example",
      "description": "syncbot-example 示例",
      "fork": false,
      "created_at": "2020-11-27T11:18:01+08:00",
      "updated_at": "2020-12-07T22:08:38+08:00",
      "pushed_at": "2020-12-07T22:06:04+08:00",
      "git_url": "git://gitee.com/open-euler/syncbot-example.git",
      "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
      "svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
      "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
      "stargazers_count": 0,
      "watchers_count": 1,
      "forks_count": 1,
      "language": "其他",
      "has_issues": true,
      "has_wiki": true,
      "has_pages": false,
      "license": "MulanPSL-2.0",
      "open_issues_count": 0,
      "default_branch": "master",
      "namespace": "open-euler",
      "name_with_namespace": "openEuler/syncbotExample",
      "path_with_namespace": "open-euler/syncbot-example"
    }
  },
  "target_branch": "master",
  "target_repo": {
    "project": {
      "id": 12940005,
      "name": "syncbotExample",
      "path": "syncbot-example",
      "full_name": "open-euler/syncbot-example",
      "owner": {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://gitee.com/open-euler/syncbot-example",
      "url": "https://gitee.com/open-euler/syncbot-example",
      "description": "syncbot-example 示例",
      "fork": false,
      "created_at": "2020-11-27T11:18:01+08:00",
      "updated_at": "2020-12-07T22:08:38+08:00",
      "pushed_at": "2020-12-07T22:06:04+08:00",
      "git_url": "git://gitee.com/open-euler/syncbot-example.git",
      "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
      "svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
      "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
      "stargazers_count": 0,
      "watchers_count": 1,
      "forks_count": 1,
      "language": "其他",
      "has_issues": true,
      "has_wiki": true,
      "has_pages": false,
      "license": "MulanPSL-2.0",
      "open_issues_count": 0,
      "default_branch": "master",
      "namespace": "open-euler",
      "name_with_namespace": "openEuler/syncbotExample",
      "path_with_namespace": "open-euler/syncbot-example"
    },
    "repository": {
      "id": 12940005,
      "name": "syncbotExample",
      "path": "syncbot-example",
      "full_name": "open-euler/syncbot-example",
      "owner": {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://gitee.com/open-euler/syncbot-example",
      "url": "https://gitee.com/open-euler/syncbot-example",
      "description": "syncbot-example 示例",
      "fork": false,
      "created_at": "2020-11-27T11:18:01+08:00",
      "updated_at": "2020-12-07T22:08:38+08:00",
      "pushed_at": "2020-12-07T22:06:04+08:00",
      "git_url": "git://gitee.com/open-euler/syncbot-example.git",
      "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
      "svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
      "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
      "stargazers_count": 0,
      "watchers_count": 1,
      "forks_count": 1,
      "language": "其他",
      "has_issues": true,
      "has_wiki": true,
      "has_pages": false,
      "license": "MulanPSL-2.0",
      "open_issues_count": 0,
      "default_branch": "master",
      "namespace": "open-euler",
      "name_with_namespace": "openEuler/syncbotExample",
      "path_with_namespace": "open-euler/syncbot-example"
    }
  },
  "project": {
    "id": 12940005,
    "name": "syncbotExample",
    "path": "syncbot-example",
    "full_name": "open-euler/syncbot-example",
    "owner": {
      "id": 341810,
      "name": "syncBot",
      "email": "custa@126.com",
      "username": "sync-bot",
      "user_name": "sync-bot",
      "url": "https://gitee.com/sync-bot",
      "login": "sync-bot",
      "avatar_url": "https://gitee.com/assets/no_portrait.png",
      "html_url": "https://gitee.com/sync-bot",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://gitee.com/open-euler/syncbot-example",
    "url": "https://gitee.com/open-euler/syncbot-example",
    "description": "syncbot-example 示例",
    "fork": false,
    "created_at": "2020-11-27T11:18:01+08:00",
    "updated_at": "2020-12-07T22:08:38+08:00",
    "pushed_at": "2020-12-07T22:06:04+08:00",
    "git_url": "git://gitee.com/open-euler/syncbot-example.git",
    "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
    "svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
    "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
    "stargazers_count": 0,
    "watchers_count": 1,
    "forks_count": 1,
    "language": "其他",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": false,
    "license": "MulanPSL-2.0",
    "open_issues_count": 0,
    "default_branch": "master",
    "namespace": "open-euler",
    "name_with_namespace": "openEuler/syncbotExample",
    "path_with_namespace": "open-euler/syncbot-example"
  },
  "repository": {
    "id": 12940005,
    "name": "syncbotExample",
    "path": "syncbot-example",
    "full_name": "open-euler/syncbot-example",
    "owner": {
      "id": 341810,
      "name": "syncBot",
      "email": "custa@126.com",
      "username": "sync-bot",
      "user_name": "sync-bot",
      "url": "https://gitee.com/sync-bot",
      "login": "sync-bot",
      "avatar_url": "https://gitee.com/assets/no_portrait.png",
      "html_url": "https://gitee.com/sync-bot",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://gitee.com/open-euler/syncbot-example",
    "url": "https://gitee.com/open-euler/syncbot-example",
    "description": "syncbot-example 示例",
    "fork": false,
    "created_at": "2020-11-27T11:18:01+08:00",
    "updated_at": "2020-12-07T22:08:38+08:00",
    "pushed_at": "2020-12-07T22:06:04+08:00",
    "git_url": "git://gitee.com/open-euler/syncbot-example.git",
    "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
    "svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
    "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
    "stargazers_count": 0,
    "watchers_count": 1,
    "forks_count": 1,
    "language": "其他",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": false,
    "license": "MulanPSL-2.0",
    "open_issues_count": 0,
    "default_branch": "master",
    "namespace": "open-euler",
    "name_with_namespace": "openEuler/syncbotExample",
    "path_with_namespace": "open-euler/syncbot-example"
  },
  "author": {
    "id": 341810,
    "name": "syncBot",
    "email": "custa@126.com",
    "username": "sync-bot",
    "user_name": "sync-bot",
    "url": "https://gitee.com/sync-bot",
    "login": "sync-bot",
    "avatar_url": "https://gitee.com/assets/no_portrait.png",
    "html_url": "https://gitee.com/sync-bot",
    "type": "User",
    "site_admin": false
  },
  "updated_by": {
    "id": 341810,
    "name": "syncBot",
    "email": "custa@126.com",
    "username": "sync-bot",
    "user_name": "sync-bot",
    "url": "https://gitee.com/sync-bot",
    "login": "sync-bot",
    "avatar_url": "https://gitee.com/assets/no_portrait.png",
    "html_url": "https://gitee.com/sync-bot",
    "type": "User",
    "site_admin": false
  },
  "sender": {
    "id": 341810,
    "name": "syncBot",
    "email": "custa@126.com",
    "username": "sync-bot",
    "user_name": "sync-bot",
    "url": "https://gitee.com/sync-bot",
    "login": "sync-bot",
    "avatar_url": "https://gitee.com/assets/no_portrait.png",
    "html_url": "https://gitee.com/sync-bot",
    "type": "User",
    "site_admin": false
  },
  "target_user": null,
  "enterprise": null,
  "hook_name": "merge_request_hooks",
  "hook_id": 491553,
  "hook_url": "https://gitee.com/open-euler/syncbot-example/hooks/491553/edit",
  "password": "",
  "timestamp": "1607350176145",
  "sign": "vR3EgAYb3VNvQO27v1XwWfO1eTo0v3PYHdhPf2Hl7sY="
}
