POST http://localhost:8765/hook
Content-Type: application/json
User-Agent: git-oschina-hook
X-Gitee-Token: Secret
X-Gitee-Timestamp: 1608223443747
X-Gitee-Ping: false
X-Gitee-Event: Merge Request Hook
X-Git-Oschina-Event: Merge Request Hook

{
  "action": "merge",
  "action_desc": null,
  "pull_request": {
    "id": 3271808,
    "number": 8,
    "state": "merged",
    "html_url": "https://gitee.com/open-euler/syncbot-example/pulls/8",
    "diff_url": "https://gitee.com/open-euler/syncbot-example/pulls/8.diff",
    "patch_url": "https://gitee.com/open-euler/syncbot-example/pulls/8.patch",
    "title": "add update foo.txt",
    "body": "",
    "labels": [

    ],
    "languages": [

    ],
    "created_at": "2020-12-23T20:25:59+08:00",
    "updated_at": "2020-12-23T20:33:18+08:00",
    "closed_at": "2020-12-23T20:33:18+08:00",
    "merged_at": "2020-12-23T20:33:18+08:00",
    "merge_commit_sha": "26e4caaccaa4d8e0a82f1d0ca85ea7bc576d25b1",
    "merge_reference_name": "refs/pull/8/MERGE",
    "user": {
      "id": 7400170,
      "name": "chenyanpanHW",
      "email": "chenyanpan@huawei.com",
      "username": "chenyanpanHW",
      "user_name": "chenyanpanHW",
      "url": "https://gitee.com/chenyanpanHW",
      "login": "chenyanpanHW",
      "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
      "html_url": "https://gitee.com/chenyanpanHW",
      "type": "User",
      "site_admin": false
    },
    "assignee": null,
    "assignees": [

    ],
    "tester": null,
    "testers": [

    ],
    "need_test": false,
    "need_review": false,
    "milestone": null,
    "head": {
      "label": "chenyanpanHW:foo",
      "ref": "foo",
      "sha": "80af8ce33fd4c23b4e8995a3bfa64ae90f87cd05",
      "user": {
        "id": 7400170,
        "name": "chenyanpanHW",
        "email": "chenyanpan@huawei.com",
        "username": "chenyanpanHW",
        "user_name": "chenyanpanHW",
        "url": "https://gitee.com/chenyanpanHW",
        "login": "chenyanpanHW",
        "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
        "html_url": "https://gitee.com/chenyanpanHW",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 12940324,
        "name": "syncbotExample",
        "path": "syncbot-example",
        "full_name": "chenyanpanHW/syncbot-example",
        "owner": {
          "id": 7400170,
          "name": "chenyanpanHW",
          "email": "chenyanpan@huawei.com",
          "username": "chenyanpanHW",
          "user_name": "chenyanpanHW",
          "url": "https://gitee.com/chenyanpanHW",
          "login": "chenyanpanHW",
          "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
          "html_url": "https://gitee.com/chenyanpanHW",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://gitee.com/chenyanpanHW/syncbot-example",
        "url": "https://gitee.com/chenyanpanHW/syncbot-example",
        "description": "syncbot-example 示例",
        "fork": true,
        "created_at": "2020-11-27T11:28:36+08:00",
        "updated_at": "2020-12-21T16:43:18+08:00",
        "pushed_at": "2020-12-21T16:43:18+08:00",
        "git_url": "git://gitee.com/chenyanpanHW/syncbot-example.git",
        "ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
        "clone_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
        "svn_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
        "git_http_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
        "git_ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
        "git_svn_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
        "homepage": null,
        "stargazers_count": 0,
        "watchers_count": 1,
        "forks_count": 0,
        "language": "other",
        "has_issues": true,
        "has_wiki": true,
        "has_pages": false,
        "license": "MulanPSL-2.0",
        "open_issues_count": 0,
        "default_branch": "master",
        "namespace": "chenyanpanHW",
        "name_with_namespace": "chenyanpanHW/syncbotExample",
        "path_with_namespace": "chenyanpanHW/syncbot-example"
      }
    },
    "base": {
      "label": "openEuler:master",
      "ref": "master",
      "sha": "3ea6a00f4642cc385843d13b9f310052f1376515",
      "user": {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 12940005,
        "name": "syncbotExample",
        "path": "syncbot-example",
        "full_name": "open-euler/syncbot-example",
        "owner": {
          "id": 341810,
          "name": "syncBot",
          "email": "custa@126.com",
          "username": "sync-bot",
          "user_name": "sync-bot",
          "url": "https://gitee.com/sync-bot",
          "login": "sync-bot",
          "avatar_url": "https://gitee.com/assets/no_portrait.png",
          "html_url": "https://gitee.com/sync-bot",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://gitee.com/open-euler/syncbot-example",
        "url": "https://gitee.com/open-euler/syncbot-example",
        "description": "syncbot-example 示例",
        "fork": false,
        "created_at": "2020-11-27T11:18:01+08:00",
        "updated_at": "2020-12-23T20:25:59+08:00",
        "pushed_at": "2020-12-21T16:44:23+08:00",
        "git_url": "git://gitee.com/open-euler/syncbot-example.git",
        "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
        "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
        "svn_url": "svn://gitee.com/open-euler/syncbot-example",
        "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
        "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
        "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
        "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
        "stargazers_count": 0,
        "watchers_count": 1,
        "forks_count": 1,
        "language": "other",
        "has_issues": true,
        "has_wiki": true,
        "has_pages": false,
        "license": "MulanPSL-2.0",
        "open_issues_count": 2,
        "default_branch": "master",
        "namespace": "open-euler",
        "name_with_namespace": "openEuler/syncbotExample",
        "path_with_namespace": "open-euler/syncbot-example"
      }
    },
    "merged": true,
    "mergeable": true,
    "merge_status": "can_be_merged",
    "updated_by": {
      "id": 341810,
      "name": "syncBot",
      "email": "custa@126.com",
      "username": "sync-bot",
      "user_name": "sync-bot",
      "url": "https://gitee.com/sync-bot",
      "login": "sync-bot",
      "avatar_url": "https://gitee.com/assets/no_portrait.png",
      "html_url": "https://gitee.com/sync-bot",
      "type": "User",
      "site_admin": false
    },
    "comments": 3,
    "commits": 2,
    "additions": 1,
    "deletions": 0,
    "changed_files": 1
  },
  "number": 8,
  "iid": 8,
  "title": "add update foo.txt",
  "body": "",
  "languages": [

  ],
  "state": "merged",
  "merge_status": "can_be_merged",
  "merge_commit_sha": "26e4caaccaa4d8e0a82f1d0ca85ea7bc576d25b1",
  "url": "https://gitee.com/open-euler/syncbot-example/pulls/8",
  "source_branch": "foo",
  "source_repo": {
    "project": {
      "id": 12940324,
      "name": "syncbotExample",
      "path": "syncbot-example",
      "full_name": "chenyanpanHW/syncbot-example",
      "owner": {
        "id": 7400170,
        "name": "chenyanpanHW",
        "email": "chenyanpan@huawei.com",
        "username": "chenyanpanHW",
        "user_name": "chenyanpanHW",
        "url": "https://gitee.com/chenyanpanHW",
        "login": "chenyanpanHW",
        "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
        "html_url": "https://gitee.com/chenyanpanHW",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://gitee.com/chenyanpanHW/syncbot-example",
      "url": "https://gitee.com/chenyanpanHW/syncbot-example",
      "description": "syncbot-example 示例",
      "fork": true,
      "created_at": "2020-11-27T11:28:36+08:00",
      "updated_at": "2020-12-21T16:43:18+08:00",
      "pushed_at": "2020-12-21T16:43:18+08:00",
      "git_url": "git://gitee.com/chenyanpanHW/syncbot-example.git",
      "ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
      "clone_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
      "svn_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
      "git_http_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
      "git_ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
      "git_svn_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
      "homepage": null,
      "stargazers_count": 0,
      "watchers_count": 1,
      "forks_count": 0,
      "language": "other",
      "has_issues": true,
      "has_wiki": true,
      "has_pages": false,
      "license": "MulanPSL-2.0",
      "open_issues_count": 0,
      "default_branch": "master",
      "namespace": "chenyanpanHW",
      "name_with_namespace": "chenyanpanHW/syncbotExample",
      "path_with_namespace": "chenyanpanHW/syncbot-example"
    },
    "repository": {
      "id": 12940324,
      "name": "syncbotExample",
      "path": "syncbot-example",
      "full_name": "chenyanpanHW/syncbot-example",
      "owner": {
        "id": 7400170,
        "name": "chenyanpanHW",
        "email": "chenyanpan@huawei.com",
        "username": "chenyanpanHW",
        "user_name": "chenyanpanHW",
        "url": "https://gitee.com/chenyanpanHW",
        "login": "chenyanpanHW",
        "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
        "html_url": "https://gitee.com/chenyanpanHW",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://gitee.com/chenyanpanHW/syncbot-example",
      "url": "https://gitee.com/chenyanpanHW/syncbot-example",
      "description": "syncbot-example 示例",
      "fork": true,
      "created_at": "2020-11-27T11:28:36+08:00",
      "updated_at": "2020-12-21T16:43:18+08:00",
      "pushed_at": "2020-12-21T16:43:18+08:00",
      "git_url": "git://gitee.com/chenyanpanHW/syncbot-example.git",
      "ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
      "clone_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
      "svn_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
      "git_http_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
      "git_ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
      "git_svn_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
      "homepage": null,
      "stargazers_count": 0,
      "watchers_count": 1,
      "forks_count": 0,
      "language": "other",
      "has_issues": true,
      "has_wiki": true,
      "has_pages": false,
      "license": "MulanPSL-2.0",
      "open_issues_count": 0,
      "default_branch": "master",
      "namespace": "chenyanpanHW",
      "name_with_namespace": "chenyanpanHW/syncbotExample",
      "path_with_namespace": "chenyanpanHW/syncbot-example"
    }
  },
  "target_branch": "master",
  "target_repo": {
    "project": {
      "id": 12940005,
      "name": "syncbotExample",
      "path": "syncbot-example",
      "full_name": "open-euler/syncbot-example",
      "owner": {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://gitee.com/open-euler/syncbot-example",
      "url": "https://gitee.com/open-euler/syncbot-example",
      "description": "syncbot-example 示例",
      "fork": false,
      "created_at": "2020-11-27T11:18:01+08:00",
      "updated_at": "2020-12-23T20:25:59+08:00",
      "pushed_at": "2020-12-21T16:44:23+08:00",
      "git_url": "git://gitee.com/open-euler/syncbot-example.git",
      "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
      "svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
      "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
      "stargazers_count": 0,
      "watchers_count": 1,
      "forks_count": 1,
      "language": "other",
      "has_issues": true,
      "has_wiki": true,
      "has_pages": false,
      "license": "MulanPSL-2.0",
      "open_issues_count": 2,
      "default_branch": "master",
      "namespace": "open-euler",
      "name_with_namespace": "openEuler/syncbotExample",
      "path_with_namespace": "open-euler/syncbot-example"
    },
    "repository": {
      "id": 12940005,
      "name": "syncbotExample",
      "path": "syncbot-example",
      "full_name": "open-euler/syncbot-example",
      "owner": {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://gitee.com/open-euler/syncbot-example",
      "url": "https://gitee.com/open-euler/syncbot-example",
      "description": "syncbot-example 示例",
      "fork": false,
      "created_at": "2020-11-27T11:18:01+08:00",
      "updated_at": "2020-12-23T20:25:59+08:00",
      "pushed_at": "2020-12-21T16:44:23+08:00",
      "git_url": "git://gitee.com/open-euler/syncbot-example.git",
      "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
      "svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
      "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
      "stargazers_count": 0,
      "watchers_count": 1,
      "forks_count": 1,
      "language": "other",
      "has_issues": true,
      "has_wiki": true,
      "has_pages": false,
      "license": "MulanPSL-2.0",
      "open_issues_count": 2,
      "default_branch": "master",
      "namespace": "open-euler",
      "name_with_namespace": "openEuler/syncbotExample",
      "path_with_namespace": "open-euler/syncbot-example"
    }
  },
  "project": {
    "id": 12940005,
    "name": "syncbotExample",
    "path": "syncbot-example",
    "full_name": "open-euler/syncbot-example",
    "owner": {
      "id": 341810,
      "name": "syncBot",
      "email": "custa@126.com",
      "username": "sync-bot",
      "user_name": "sync-bot",
      "url": "https://gitee.com/sync-bot",
      "login": "sync-bot",
      "avatar_url": "https://gitee.com/assets/no_portrait.png",
      "html_url": "https://gitee.com/sync-bot",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://gitee.com/open-euler/syncbot-example",
    "url": "https://gitee.com/open-euler/syncbot-example",
    "description": "syncbot-example 示例",
    "fork": false,
    "created_at": "2020-11-27T11:18:01+08:00",
    "updated_at": "2020-12-23T20:25:59+08:00",
    "pushed_at": "2020-12-21T16:44:23+08:00",
    "git_url": "git://gitee.com/open-euler/syncbot-example.git",
    "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
    "svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
    "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
    "stargazers_count": 0,
    "watchers_count": 1,
    "forks_count": 1,
    "language": "other",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": false,
    "license": "MulanPSL-2.0",
    "open_issues_count": 2,
    "default_branch": "master",
    "namespace": "open-euler",
    "name_with_namespace": "openEuler/syncbotExample",
    "path_with_namespace": "open-euler/syncbot-example"
  },
  "repository": {
    "id": 12940005,
    "name": "syncbotExample",
    "path": "syncbot-example",
    "full_name": "open-euler/syncbot-example",
    "owner": {
      "id": 341810,
      "name": "syncBot",
      "email": "custa@126.com",
      "username": "sync-bot",
      "user_name": "sync-bot",
      "url": "https://gitee.com/sync-bot",
      "login": "sync-bot",
      "avatar_url": "https://gitee.com/assets/no_portrait.png",
      "html_url": "https://gitee.com/sync-bot",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://gitee.com/open-euler/syncbot-example",
    "url": "https://gitee.com/open-euler/syncbot-example",
    "description": "syncbot-example 示例",
    "fork": false,
    "created_at": "2020-11-27T11:18:01+08:00",
    "updated_at": "2020-12-23T20:25:59+08:00",
    "pushed_at": "2020-12-21T16:44:23+08:00",
    "git_url": "git://gitee.com/open-euler/syncbot-example.git",
    "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
    "svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
    "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
    "stargazers_count": 0,
    "watchers_count": 1,
    "forks_count": 1,
    "language": "other",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": false,
    "license": "MulanPSL-2.0",
    "open_issues_count": 2,
    "default_branch": "master",
    "namespace": "open-euler",
    "name_with_namespace": "openEuler/syncbotExample",
    "path_with_namespace": "open-euler/syncbot-example"
  },
  "author": {
    "id": 7400170,
    "name": "chenyanpanHW",
    "email": "chenyanpan@huawei.com",
    "username": "chenyanpanHW",
    "user_name": "chenyanpanHW",
    "url": "https://gitee.com/chenyanpanHW",
    "login": "chenyanpanHW",
    "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
    "html_url": "https://gitee.com/chenyanpanHW",
    "type": "User",
    "site_admin": false
  },
  "updated_by": {
    "id": 341810,
    "name": "syncBot",
    "email": "custa@126.com",
    "username": "sync-bot",
    "user_name": "sync-bot",
    "url": "https://gitee.com/sync-bot",
    "login": "sync-bot",
    "avatar_url": "https://gitee.com/assets/no_portrait.png",
    "html_url": "https://gitee.com/sync-bot",
    "type": "User",
    "site_admin": false
  },
  "sender": {
    "id": 341810,
    "name": "syncBot",
    "email": "custa@126.com",
    "username": "sync-bot",
    "user_name": "sync-bot",
    "url": "https://gitee.com/sync-bot",
    "login": "sync-bot",
    "avatar_url": "https://gitee.com/assets/no_portrait.png",
    "html_url": "https://gitee.com/sync-bot",
    "type": "User",
    "site_admin": false
  },
  "target_user": null,
  "enterprise": null,
  "hook_name": "merge_request_hooks",
  "hook_id": 491553,
  "hook_url": "https://gitee.com/open-euler/syncbot-example/hooks/491553/edit",
  "password": "Secret",
  "timestamp": "1608726798778",
  "sign": ""
}
