POST http://127.0.0.1:1234/hook
Content-Type: application/json
Accept: application/json
X-Gitee-Event: Note Hook
X-Gitee-Token: Secret

{
  "action": "comment",
  "comment": {
    "id": 3775660,
    "body": "/sync-check\n",
    "user": {
      "id": 341810,
      "name": "syncBot",
      "email": "custa@126.com",
      "username": "sync-bot",
      "user_name": "sync-bot",
      "url": "https://gitee.com/sync-bot",
      "login": "sync-bot",
      "avatar_url": "https://gitee.com/assets/no_portrait.png",
      "html_url": "https://gitee.com/sync-bot",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-12-07T00:39:10+08:00",
    "updated_at": "2020-12-07T00:39:10+08:00",
    "html_url": "https://gitee.com/open-euler/syncbot-example/pulls/3#note_3775660"
  },
  "repository": {
    "id": 12940005,
    "name": "syncbotExample",
    "path": "syncbot-example",
    "full_name": "open-euler/syncbot-example",
    "owner": {
      "id": 341810,
      "name": "syncBot",
      "email": "custa@126.com",
      "username": "sync-bot",
      "user_name": "sync-bot",
      "url": "https://gitee.com/sync-bot",
      "login": "sync-bot",
      "avatar_url": "https://gitee.com/assets/no_portrait.png",
      "html_url": "https://gitee.com/sync-bot",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://gitee.com/open-euler/syncbot-example",
    "url": "https://gitee.com/open-euler/syncbot-example",
    "description": "syncbot-example 示例",
    "fork": false,
    "created_at": "2020-11-27T11:18:01+08:00",
    "updated_at": "2020-11-27T15:19:14+08:00",
    "pushed_at": "2020-11-27T14:27:23+08:00",
    "git_url": "git://gitee.com/open-euler/syncbot-example.git",
    "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
    "svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
    "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
    "stargazers_count": 0,
    "watchers_count": 1,
    "forks_count": 1,
    "language": "其他",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": false,
    "license": "MulanPSL-2.0",
    "open_issues_count": 0,
    "default_branch": "master",
    "namespace": "open-euler",
    "name_with_namespace": "openEuler/syncbotExample",
    "path_with_namespace": "open-euler/syncbot-example"
  },
  "project": {
    "id": 12940005,
    "name": "syncbotExample",
    "path": "syncbot-example",
    "full_name": "open-euler/syncbot-example",
    "owner": {
      "id": 341810,
      "name": "syncBot",
      "email": "custa@126.com",
      "username": "sync-bot",
      "user_name": "sync-bot",
      "url": "https://gitee.com/sync-bot",
      "login": "sync-bot",
      "avatar_url": "https://gitee.com/assets/no_portrait.png",
      "html_url": "https://gitee.com/sync-bot",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://gitee.com/open-euler/syncbot-example",
    "url": "https://gitee.com/open-euler/syncbot-example",
    "description": "syncbot-example 示例",
    "fork": false,
    "created_at": "2020-11-27T11:18:01+08:00",
    "updated_at": "2020-11-27T15:19:14+08:00",
    "pushed_at": "2020-11-27T14:27:23+08:00",
    "git_url": "git://gitee.com/open-euler/syncbot-example.git",
    "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
    "svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
    "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
    "stargazers_count": 0,
    "watchers_count": 1,
    "forks_count": 1,
    "language": "其他",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": false,
    "license": "MulanPSL-2.0",
    "open_issues_count": 0,
    "default_branch": "master",
    "namespace": "open-euler",
    "name_with_namespace": "openEuler/syncbotExample",
    "path_with_namespace": "open-euler/syncbot-example"
  },
  "author": {
    "id": 341810,
    "name": "syncBot",
    "email": "custa@126.com",
    "username": "sync-bot",
    "user_name": "sync-bot",
    "url": "https://gitee.com/sync-bot",
    "login": "sync-bot",
    "avatar_url": "https://gitee.com/assets/no_portrait.png",
    "html_url": "https://gitee.com/sync-bot",
    "type": "User",
    "site_admin": false
  },
  "sender": {
    "id": 341810,
    "name": "syncBot",
    "email": "custa@126.com",
    "username": "sync-bot",
    "user_name": "sync-bot",
    "url": "https://gitee.com/sync-bot",
    "login": "sync-bot",
    "avatar_url": "https://gitee.com/assets/no_portrait.png",
    "html_url": "https://gitee.com/sync-bot",
    "type": "User",
    "site_admin": false
  },
  "url": "https://gitee.com/open-euler/syncbot-example/pulls/3#note_3775660",
  "note": "/sync-check\n",
  "noteable_type": "PullRequest",
  "noteable_id": 3142460,
  "title": "foo",
  "per_iid": "!3",
  "short_commit_id": null,
  "enterprise": null,
  "pull_request": {
    "id": 3142460,
    "number": 3,
    "state": "open",
    "html_url": "https://gitee.com/open-euler/syncbot-example/pulls/3",
    "diff_url": "https://gitee.com/open-euler/syncbot-example/pulls/3.diff",
    "patch_url": "https://gitee.com/open-euler/syncbot-example/pulls/3.patch",
    "title": "foo",
    "body": "Foo\r\n",
    "labels": [
      {
        "id": 88897226,
        "name": "question",
        "color": "00B5AD"
      }
    ],
    "languages": [],
    "created_at": "2020-11-27T15:19:14+08:00",
    "updated_at": "2020-12-07T00:39:10+08:00",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": "a40beff7bbcd97cbb8c3d439805e0164f26f621c",
    "merge_reference_name": "refs/pull/3/MERGE",
    "user": {
      "id": 7400170,
      "name": "chenyanpanHW",
      "email": "chenyanpan@huawei.com",
      "username": "chenyanpanHW",
      "user_name": "chenyanpanHW",
      "url": "https://gitee.com/chenyanpanHW",
      "login": "chenyanpanHW",
      "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
      "html_url": "https://gitee.com/chenyanpanHW",
      "type": "User",
      "site_admin": false
    },
    "assignee": null,
    "assignees": [
      {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      }
    ],
    "tester": null,
    "testers": [
      {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      }
    ],
    "need_test": false,
    "need_review": false,
    "milestone": null,
    "head": {
      "label": "chenyanpanHW:foo",
      "ref": "foo",
      "sha": "80af8ce33fd4c23b4e8995a3bfa64ae90f87cd05",
      "user": {
        "id": 7400170,
        "name": "chenyanpanHW",
        "email": "chenyanpan@huawei.com",
        "username": "chenyanpanHW",
        "user_name": "chenyanpanHW",
        "url": "https://gitee.com/chenyanpanHW",
        "login": "chenyanpanHW",
        "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
        "html_url": "https://gitee.com/chenyanpanHW",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 12940324,
        "name": "syncbotExample",
        "path": "syncbot-example",
        "full_name": "chenyanpanHW/syncbot-example",
        "owner": {
          "id": 7400170,
          "name": "chenyanpanHW",
          "email": "chenyanpan@huawei.com",
          "username": "chenyanpanHW",
          "user_name": "chenyanpanHW",
          "url": "https://gitee.com/chenyanpanHW",
          "login": "chenyanpanHW",
          "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
          "html_url": "https://gitee.com/chenyanpanHW",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://gitee.com/chenyanpanHW/syncbot-example",
        "url": "https://gitee.com/chenyanpanHW/syncbot-example",
        "description": "syncbot-example 示例",
        "fork": true,
        "created_at": "2020-11-27T11:28:36+08:00",
        "updated_at": "2020-11-27T11:39:25+08:00",
        "pushed_at": "2020-11-27T11:39:25+08:00",
        "git_url": "git://gitee.com/chenyanpanHW/syncbot-example.git",
        "ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
        "clone_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
        "svn_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
        "git_http_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
        "git_ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
        "git_svn_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
        "homepage": null,
        "stargazers_count": 0,
        "watchers_count": 1,
        "forks_count": 0,
        "language": "其他",
        "has_issues": true,
        "has_wiki": true,
        "has_pages": false,
        "license": "MulanPSL-2.0",
        "open_issues_count": 0,
        "default_branch": "master",
        "namespace": "chenyanpanHW",
        "name_with_namespace": "chenyanpanHW/syncbotExample",
        "path_with_namespace": "chenyanpanHW/syncbot-example"
      }
    },
    "base": {
      "label": "openEuler:master",
      "ref": "master",
      "sha": "3ea6a00f4642cc385843d13b9f310052f1376515",
      "user": {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 12940005,
        "name": "syncbotExample",
        "path": "syncbot-example",
        "full_name": "open-euler/syncbot-example",
        "owner": {
          "id": 341810,
          "name": "syncBot",
          "email": "custa@126.com",
          "username": "sync-bot",
          "user_name": "sync-bot",
          "url": "https://gitee.com/sync-bot",
          "login": "sync-bot",
          "avatar_url": "https://gitee.com/assets/no_portrait.png",
          "html_url": "https://gitee.com/sync-bot",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://gitee.com/open-euler/syncbot-example",
        "url": "https://gitee.com/open-euler/syncbot-example",
        "description": "syncbot-example 示例",
        "fork": false,
        "created_at": "2020-11-27T11:18:01+08:00",
        "updated_at": "2020-11-27T15:19:14+08:00",
        "pushed_at": "2020-11-27T14:27:23+08:00",
        "git_url": "git://gitee.com/open-euler/syncbot-example.git",
        "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
        "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
        "svn_url": "svn://gitee.com/open-euler/syncbot-example",
        "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
        "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
        "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
        "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
        "stargazers_count": 0,
        "watchers_count": 1,
        "forks_count": 1,
        "language": "其他",
        "has_issues": true,
        "has_wiki": true,
        "has_pages": false,
        "license": "MulanPSL-2.0",
        "open_issues_count": 0,
        "default_branch": "master",
        "namespace": "open-euler",
        "name_with_namespace": "openEuler/syncbotExample",
        "path_with_namespace": "open-euler/syncbot-example"
      }
    },
    "merged": false,
    "mergeable": true,
    "merge_status": "can_be_merged",
    "updated_by": {
      "id": 341810,
      "name": "syncBot",
      "email": "custa@126.com",
      "username": "sync-bot",
      "user_name": "sync-bot",
      "url": "https://gitee.com/sync-bot",
      "login": "sync-bot",
      "avatar_url": "https://gitee.com/assets/no_portrait.png",
      "html_url": "https://gitee.com/sync-bot",
      "type": "User",
      "site_admin": false
    },
    "comments": 8,
    "commits": 2,
    "additions": 1,
    "deletions": 0,
    "changed_files": 1
  },
  "hook_name": "note_hooks",
  "hook_id": 491553,
  "hook_url": "https://gitee.com/open-euler/syncbot-example/hooks/491553/edit",
  "password": "",
  "timestamp": "1607272751158",
  "sign": "yqUyNuhaSO+QRUz3kVGDk+gLYKbXDRSiOIviAfr9m8g="
}

